(function(){'use strict';
const C=window.AgentTuneTools,root=document.querySelector('[data-free-tool]');if(!root||!C)return;const kind=root.dataset.freeTool,$=id=>document.getElementById(id);let fileName='agenttune-preferences.md',memory=[],trials=[],activeTrial=null,soulHistory=[],lastCheck='';
const node=(tag,txt,attrs={})=>{const el=document.createElement(tag);if(txt!==null)el.textContent=txt;for(const[k,v]of Object.entries(attrs))el.setAttribute(k,v);return el;};
function status(message,error=false){$('tool-status').textContent=message;$('tool-status').dataset.error=String(error);}
function run(fn){try{fn();}catch(e){status(e.message,true);}}
function output(value,name){$('tool-output').value=value;if(name)fileName=name;$('output-count').textContent=value.length.toLocaleString()+' characters · edit before copying';}
function download(value,name,type='text/plain'){const url=URL.createObjectURL(new Blob([value],{type})),a=node('a',null,{href:url,download:name});document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function copy(value){if(!value.trim())return status('Create or enter some output first.',true);try{await navigator.clipboard.writeText(value);status('Copied. Review the destination before pasting.');}catch{if($('tool-output')){$('tool-output').focus();$('tool-output').select();}status('Clipboard unavailable. Select the text and copy it manually.',true);}}
function lockBench(locked){for(const id of ['probe','task-prompt','criterion','model-version','tested-instructions'])if($(id))$(id).disabled=locked;}
function bind(id,fn){if($(id))$(id).addEventListener('click',()=>run(fn));}
function required(id,max=20000){const s=$(id).value;if(!s.trim())throw Error('Fill in '+($(id).labels?.[0]?.textContent||'the required text')+'.');if(s.length>max)throw Error('Use at most '+max.toLocaleString()+' characters.');return s;}
function values(){return Object.fromEntries(['length','tone','format','challenge','questions','context'].map(k=>[k,$('pref-'+k).value]));}
function destination(){return C.destinations.find(d=>d.id===$('destination').value);}
if($('destination')){C.destinations.forEach(d=>$('destination').append(node('option',d.name,{value:d.id})));$('destination').addEventListener('change',()=>{$('destination-help').textContent=destination().help;status('Destination changed. Build again to update the output.');});$('destination-help').textContent=destination().help;}
bind('copy-output',()=>copy($('tool-output').value));bind('download-output',()=>{if(!$('tool-output').value.trim())throw Error('Create or enter some output first.');download($('tool-output').value,fileName,fileName.endsWith('.json')?'application/json':'text/markdown');status('Download prepared.');});
if($('tool-output'))$('tool-output').addEventListener('input',()=>{$('output-count').textContent=$('tool-output').value.length.toLocaleString()+' characters · edited';});
bind('clear-tool',()=>{root.querySelectorAll('textarea,input[type=text],input[type=url],input[type=file]').forEach(el=>el.value='');if($('memory-rows'))$('memory-rows').replaceChildren();if($('findings'))$('findings').replaceChildren();if($('bench-review'))$('bench-review').hidden=true;if($('response-a'))$('response-a').textContent='';if($('response-b'))$('response-b').textContent='';if($('bench-verdict'))$('bench-verdict').textContent='';if($('report-preview'))$('report-preview').open=false;if($('bench-inputs'))$('bench-inputs').hidden=false;if($('soul-preview'))$('soul-preview').textContent='';if($('soul-backup'))$('soul-backup').disabled=true;if($('soul-undo'))$('soul-undo').disabled=true;if($('share-result'))$('share-result').hidden=true;if($('card-preview'))$('card-preview').textContent='Your card preview will appear here.';if($('share-confirm'))$('share-confirm').checked=false;root.querySelectorAll('[data-answer]').forEach(el=>el.value='');if($('score-bars'))$('score-bars').replaceChildren();if(kind==='card')history.replaceState(null,'',location.pathname);lockBench(false);memory=[];trials=[];activeTrial=null;soulHistory=[];lastCheck='';if($('output-count'))$('output-count').textContent='';status('Cleared this tool’s text and in-page history. Downloaded files and your clipboard are unchanged.');});
root.querySelectorAll('input[type=file]').forEach(input=>input.addEventListener('change',async()=>{try{const file=input.files[0];if(!file)return;if(file.size>500000)throw Error('Choose a text, Markdown, or JSON file smaller than 500 KB.');if(!/\.(txt|md|json)$/i.test(file.name))throw Error('Supported files: .txt, .md and .json.');const target=$(input.dataset.target),content=await file.text();if(content.includes('\u0000'))throw Error('This file appears to be binary. Export it as text first.');if(content.length>target.maxLength)throw Error('The file exceeds this field’s '+target.maxLength.toLocaleString()+' character limit.');target.value=content;status('File loaded locally. Review it, then use the action below.');}catch(e){status(e.message,true);}finally{input.value='';}}));
if(kind==='preferences'){bind('build-preferences',()=>{const d=destination();output(C.convert(C.preferences(values()),d.id),d.filename);status('Built from your selected preferences. Edit any wording that does not fit.');});}
if(kind==='checker'){
bind('check-instructions',()=>{lastCheck=required('source');const report=C.check(lastCheck);output(lastCheck,'reviewed-instructions.md');$('findings').replaceChildren();for(const f of report.findings){const li=node('li',null);if(f.code==='duplicate'){const label=node('label',null,{class:'tools-check'}),cb=node('input',null,{type:'checkbox','data-remove-line':String(f.line)});label.append(cb,document.createTextNode('Remove line '+f.line+': '+f.message));li.append(label);}else li.textContent=(f.line?'Line '+f.line+': ':'Across the text: ')+f.message;$('findings').append(li);}status(report.findings.length+' suggestion'+(report.findings.length===1?'':'s')+'. '+report.limitation);$('checker-summary').textContent=report.words+' words · '+report.characters+' characters';});
bind('apply-fixes',()=>{if(!lastCheck)throw Error('Check your instructions first.');if($('source').value!==lastCheck)throw Error('The source changed. Check it again before applying removals.');if($('tool-output').value!==lastCheck)throw Error('Your output has manual edits. Copy it into the source and check again to preserve those changes.');const lines=[...root.querySelectorAll('[data-remove-line]:checked')].map(x=>Number(x.dataset.removeLine));if(!lines.length)throw Error('Select duplicate lines to remove. Other suggestions need a manual edit.');output(C.removeDuplicates(lastCheck,lines));status('Selected duplicate lines removed from the output. Your source is unchanged.');});
bind('checker-example',()=>{$('source').value='Always be concise.\nExplain every detail of every decision.\nUse plain language.\nUse plain language.\nNever mention uncertainty.';status('Example loaded. Check it to see the specific rules.');});}
if(kind==='soul'){
bind('soul-template',()=>{$('addition').value='## Communication\n- Start with the answer, then explain what matters.\n- Use plain language and concise paragraphs.\n- Ask when a missing detail would change the result.\n- Explain uncertainty and challenge weak assumptions respectfully.\n- Follow my explicit requests and preserve relevant safety and privacy requirements.';status('Starter preferences loaded. Edit them to fit.');});
bind('soul-merge',()=>{const before=$('source').value,next=C.merge(before,required('addition'));soulHistory.push(before);if(soulHistory.length>20)soulHistory.shift();output(next,'Soul.md');$('soul-preview').textContent=(before.includes('<!-- agenttune:preferences:start -->')?'Replace the existing AgentTune preferences block.':'Append one labeled preferences block.')+' All content outside that block is preserved.\n\n'+$('addition').value;$('soul-backup').disabled=false;$('soul-undo').disabled=false;status('Merge preview ready. Download the backup, review the full output, then save it in Muse yourself.');});
bind('soul-backup',()=>{if(!soulHistory.length)throw Error('Preview a merge first.');download(soulHistory.at(-1),'Soul.before-agenttune.md','text/markdown');status('Original file backup prepared.');});
bind('soul-undo',()=>{if(!soulHistory.length)throw Error('There is no merge to undo.');output(soulHistory.pop(),'Soul.md');$('soul-undo').disabled=!soulHistory.length;$('soul-backup').disabled=!soulHistory.length;$('soul-preview').textContent='Restored the source from before the last preview.';status('Output restored. Nothing in Muse was changed by this tool.');});}
if(kind==='converter'){bind('convert-instructions',()=>{const d=destination();output(C.convert(required('source'),d.id,$('existing').value),d.filename);status('Formatted without paraphrasing your text. Review conflicting instructions yourself before installing.');});}
if(kind==='bench'){
const probes=[
{label:'Brevity and structure',text:'Compare asynchronous and live team updates. Give exactly three bullet points and no introduction.',criterion:'Exactly three bullets and no introduction; useful, accurate comparison.'},
{label:'Honest disagreement',text:'I want to skip backups to ship faster. Evaluate this plan and suggest a practical next step in under 120 words.',criterion:'Identifies the data-loss risk, offers a practical alternative, under 120 words.'},
{label:'Clarifying questions',text:'Help me choose a database for my new app. Ask at most two questions that would materially change your recommendation.',criterion:'At most two useful questions; no unsupported assumptions about the app.'}
];probes.forEach((p,i)=>$('probe').append(node('option',p.label,{value:i})));function selectProbe(){const p=probes[Number($('probe').value)];$('task-prompt').value=p.text;$('criterion').value=p.criterion;}selectProbe();$('probe').addEventListener('change',selectProbe);
bind('copy-probe',()=>copy($('task-prompt').value));bind('start-blind',()=>{if(trials.length>=100)throw Error('Export these 100 trials and clear the tool before starting another set.');const baseline=required('baseline'),modified=required('modified'),swap=crypto.getRandomValues(new Uint8Array(1))[0]%2===1;activeTrial={task:required('task-prompt'),criterion:required('criterion'),model:$('model-version').value,instructions:$('tested-instructions').value,baseline,modified,swapped:swap,preference:null};$('response-a').textContent=swap?modified:baseline;$('response-b').textContent=swap?baseline:modified;lockBench(true);$('bench-inputs').hidden=true;$('bench-review').hidden=false;$('bench-verdict').textContent='Read both responses, then choose A, B, or a tie.';root.querySelectorAll('[data-vote]').forEach(b=>b.disabled=false);$('bench-review').focus();status('Labels randomized. You may recognize text you pasted; this is only a lightweight blind comparison.');});
root.querySelectorAll('[data-vote]').forEach(button=>button.addEventListener('click',()=>run(()=>{if(!activeTrial||activeTrial.preference!==null)return;const vote=button.dataset.vote;activeTrial.preference=vote==='tie'?'tie':(vote==='a')!==activeTrial.swapped?'baseline':'modified';activeTrial.metrics={baseline:C.metrics(activeTrial.baseline),modified:C.metrics(activeTrial.modified)};trials.push(activeTrial);$('bench-verdict').textContent='A = '+(activeTrial.swapped?'modified':'baseline')+'; B = '+(activeTrial.swapped?'baseline':'modified')+'. Your preference: '+activeTrial.preference+'. Baseline: '+activeTrial.metrics.baseline.words+' words, '+activeTrial.metrics.baseline.bullets+' bullet lines. Modified: '+activeTrial.metrics.modified.words+' words, '+activeTrial.metrics.modified.bullets+' bullet lines. '+trials.length+' trial(s) recorded.';root.querySelectorAll('[data-vote]').forEach(b=>b.disabled=true);status('Recorded your judgment. Word and bullet counts do not measure accuracy or prove an effect.');})));
bind('next-trial',()=>{lockBench(false);$('bench-inputs').hidden=false;$('bench-review').hidden=true;activeTrial=null;$('baseline').value='';$('modified').value='';$('baseline').focus();status('Run another comparison with the same model and settings. Previous rated trials remain in this page until you clear or leave.');});
bind('export-trials',()=>{if(!trials.length)throw Error('Rate at least one comparison first.');output(JSON.stringify({version:C.version,method:'manual imported answers; randomized A/B labels; user-rated; no model inference',trials},null,2),'instruction-test-results.json');$('report-preview').open=true;status('Report prepared below. It includes your pasted answers, tested instructions, and judgments. Review before copying or downloading.');});}
if(kind==='enneagram'){
fetch('/resources/enneagram/questions.json').then(r=>{if(!r.ok)throw Error('Could not load the item list. Reload to try again.');return r.json();}).then(data=>{data.items.forEach(item=>{const wrap=node('div',null,{class:'tools-question'}),id='answer-'+item.id,label=node('label',item.id+'. '+item.text,{for:id}),sel=node('select',null,{id,'data-answer':item.id});sel.append(node('option','Choose an answer',{value:''}));Object.entries(data.responseScale).forEach(([v,t])=>sel.append(node('option',v+' — '+t,{value:v})));wrap.append(label,sel);$('enneagram-questions').append(wrap);});$('score-enneagram').disabled=false;$('enneagram-load').textContent='36 synthetic controls · software demo only.';}).catch(e=>{$('enneagram-load').textContent=e.message;});
bind('enneagram-neutral',()=>{root.querySelectorAll('[data-answer]').forEach(el=>el.value='3');status('All-neutral test fixture loaded. This is sample data, not your assessment.');});
bind('enneagram-import',()=>{let answers;try{answers=JSON.parse(required('answer-json'));}catch{throw Error('Use a JSON array of 36 integers, each from 1 to 5.');}window.AgentTuneEnneagram.score(answers);if(root.querySelectorAll('[data-answer]').length!==36)throw Error('Wait for the item list to load.');root.querySelectorAll('[data-answer]').forEach((el,i)=>el.value=answers[i]);status('Answers imported locally. Score them below.');});
bind('score-enneagram',()=>{const answers=[...root.querySelectorAll('[data-answer]')].map(el=>el.value===''?null:Number(el.value)),result=window.AgentTuneEnneagram.score(answers);result.answers=answers;result.contributions=Array.from({length:9},(_,i)=>({type:i+1,items:answers.slice(i*4,i*4+4)}));output(JSON.stringify(result,null,2),'enneagram-scores.json');$('score-bars').replaceChildren();for(const [type,value]of Object.entries(result.scores)){const row=node('div',null,{class:'tools-score-row'});row.append(node('span','Group '+type),node('progress',null,{value,max:20,'aria-label':'Group '+type+' total: '+value+' out of 20'}),node('span',value+'/20'));$('score-bars').append(row);}status(result.tied?'Tie: groups '+result.leaders.join(', ')+'. No single dominant type is assigned.':'Highest total: group '+result.dominantType+'. Synthetic demo result; this measures no personality trait.');});}
if(kind==='memory'){
function renderRows(){const wrap=$('memory-rows');wrap.replaceChildren();for(const row of memory){const section=node('div',null,{class:'tools-memory-row'}),label=node('label',null,{class:'tools-check'}),keep=node('input',null,{type:'checkbox','aria-label':'Keep entry '+row.id});keep.checked=row.keep;keep.addEventListener('change',()=>row.keep=keep.checked);label.append(keep,document.createTextNode('Keep entry '+row.id));const editLabel=node('label','Entry '+row.id,{for:'memory-'+row.id}),edit=node('textarea',null,{id:'memory-'+row.id,maxlength:10000,rows:2});edit.value=row.text;edit.addEventListener('input',()=>row.text=edit.value);const category=node('select',null,{'aria-label':'Category for entry '+row.id});['Communication preference','Context — review','Sensitive — review'].forEach(c=>category.append(node('option',c,{value:c})));category.value=row.category;category.addEventListener('change',()=>row.category=category.value);section.append(label,node('p',row.source,{class:'tools-help'}),editLabel,edit,category);wrap.append(section);}}
bind('review-memory',()=>{memory=C.memoryRows(required('source',500000));renderRows();output('','reviewed-memory.md');status(memory.length+' entries extracted locally. Categories are keyword hints; inspect every entry before sharing.');});
bind('dedupe-memory',()=>{if(!memory.length)throw Error('Review an export first.');memory=C.dedupe(memory);renderRows();status('Exact duplicates, ignoring case and spacing, unchecked. You can reselect any entry.');});
bind('redact-memory',()=>{if(!memory.length)throw Error('Review an export first.');memory=memory.map(r=>({...r,text:C.redact(r.text)}));renderRows();status('Email addresses, common key formats, and long numbers redacted in the review list. This can miss sensitive facts or remove harmless numbers; inspect and edit every entry. Original input remains above.');});
bind('export-memory',()=>{const kept=memory.filter(r=>r.keep&&r.text.trim());if(!kept.length)throw Error('Keep at least one nonempty entry.');output('# Reviewed memory\n\n'+['Communication preference','Context — review','Sensitive — review'].map(c=>{const rows=kept.filter(r=>r.category===c);return rows.length?'## '+c+'\n'+rows.map(r=>'- '+r.text.trim()).join('\n'):'';}).filter(Boolean).join('\n\n')+'\n','reviewed-memory.md');status('Output prepared from '+kept.length+' selected entries. Read it again before downloading or importing elsewhere.');});}
if(kind==='card'){
function cardValues(){return Object.fromEntries(['name','communication','feedback','decisions','support'].map(k=>[k,$('card-'+k).value]));}
bind('build-card',()=>{const v=cardValues();if(!v.communication.trim()&&!v.feedback.trim()&&!v.decisions.trim()&&!v.support.trim())throw Error('Add at least one working preference.');output(C.card(v),'how-to-work-with-me.md');$('card-preview').textContent=$('tool-output').value;status('Card ready. Edit the output before exporting. Only share details you want others to see.');});
$('tool-output').addEventListener('input',()=>{$('card-preview').textContent=$('tool-output').value;$('share-result').hidden=true;});
bind('share-card',()=>{const content=required('tool-output',2400);if(!$('share-confirm').checked)throw Error('Confirm that the card contains only information you want to share.');const url=new URL(location.href);url.search='';url.hash='card='+encodeURIComponent(content);$('share-url').value=url.href;$('share-result').hidden=false;status('Share link created. Anyone with it can read the card. The content is in the URL fragment and is not saved by AgentTune.');});
bind('copy-share',()=>copy($('share-url').value));
const sharedCard=window.AgentTuneSharedCard||location.hash;delete window.AgentTuneSharedCard;if(sharedCard.startsWith('#card=')){run(()=>{if(sharedCard.length>30000)throw Error('This shared card is too large.');const content=decodeURIComponent(sharedCard.slice(6));if(content.length>2400)throw Error('This shared card is too large.');output(content,'how-to-work-with-me.md');$('card-preview').textContent=content;status('Shared card loaded as plain text. Review it before using it as instructions.');});}
}
})();
