#!/usr/bin/env python3
"""Inject breadcrumb nav + JSON-LD into hand-coded HTML pages.

Pages handled here:
- /tests/index.html        Home › Tests
- /tests/{five-tests}.html Home › Tests › {Name}
- /research.html           Home › Research
- /pricing.html            Home › Pricing

Library pages (/library/* and /library/{system}/*) are generated by
tools/generate-library.js, which has its own breadcrumb rendering.
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE = "https://agent-tune.com"

PAGES = [
    # rel_path, breadcrumb_trail
    # trail: [(name, url_or_None_if_current), ...]
    ("tests/index.html", [
        ("Home", "/"),
        ("Tests", None),
    ]),
    ("tests/mbti.html", [
        ("Home", "/"),
        ("Tests", "/tests/"),
        ("MBTI", None),
    ]),
    ("tests/enneagram.html", [
        ("Home", "/"),
        ("Tests", "/tests/"),
        ("Enneagram", None),
    ]),
    ("tests/disc.html", [
        ("Home", "/"),
        ("Tests", "/tests/"),
        ("DISC", None),
    ]),
    ("tests/attachment.html", [
        ("Home", "/"),
        ("Tests", "/tests/"),
        ("Attachment", None),
    ]),
    ("tests/big-five.html", [
        ("Home", "/"),
        ("Tests", "/tests/"),
        ("Big Five", None),
    ]),
    ("research.html", [
        ("Home", "/"),
        ("Research", None),
    ]),
    ("pricing.html", [
        ("Home", "/"),
        ("Pricing", None),
    ]),
]


def html_breadcrumb(trail):
    """Build the visible breadcrumb nav HTML."""
    parts = []
    for i, (name, url) in enumerate(trail):
        if i > 0:
            parts.append('<span class="crumb-sep" aria-hidden="true">›</span>')
        if url is None:
            parts.append(f'<span class="crumb-current" aria-current="page">{name}</span>')
        else:
            parts.append(f'<a href="{url}">{name}</a>')
    inner = "\n      ".join(parts)
    return f'<nav class="breadcrumbs" aria-label="Breadcrumb">\n      {inner}\n    </nav>'


def jsonld_breadcrumb(trail):
    """Build the schema.org BreadcrumbList JSON-LD."""
    items = []
    for i, (name, url) in enumerate(trail):
        item = {
            "@type": "ListItem",
            "position": i + 1,
            "name": name,
        }
        if url is not None:
            item["item"] = BASE + url
        items.append(item)
    payload = {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": items,
    }
    return f'<script type="application/ld+json">{json.dumps(payload, separators=(",", ":"))}</script>'


# Pattern: end of primary nav block — we insert breadcrumbs just after it.
# The nav block ends with "</nav>" and we insert before the next non-whitespace content.
NAV_END_RE = re.compile(
    r'(</nav>)(\s*)',
)


def inject(html, trail):
    """Insert breadcrumb nav after the primary </nav> and JSON-LD before </head>."""
    # Only act if not already injected
    if 'class="breadcrumbs"' in html:
        return html, False

    # Insert visible breadcrumb after the FIRST </nav>
    crumb_html = html_breadcrumb(trail)
    new_html, count = NAV_END_RE.subn(
        lambda m: f'{m.group(1)}\n\n    {crumb_html}{m.group(2)}',
        html,
        count=1,
    )
    if count == 0:
        return html, False

    # Insert JSON-LD just before </head>
    ld = jsonld_breadcrumb(trail)
    if "</head>" in new_html:
        new_html = new_html.replace("</head>", f"  {ld}\n</head>", 1)

    return new_html, True


def main():
    for rel, trail in PAGES:
        path = os.path.join(ROOT, rel)
        if not os.path.exists(path):
            print(f"MISSING: {rel}")
            continue
        with open(path, "r", encoding="utf-8") as f:
            html = f.read()
        new_html, changed = inject(html, trail)
        if changed:
            with open(path, "w", encoding="utf-8") as f:
                f.write(new_html)
            print(f"OK:   {rel}")
        else:
            print(f"SKIP: {rel} (already has breadcrumbs or no nav anchor)")


if __name__ == "__main__":
    main()
