const fs=require('node:fs'),path=require('node:path'),content=require('./content-bundle.cjs')();
const write=(p,s)=>fs.writeFileSync(path.join(content.root,p),s);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const inline=x=>JSON.stringify(x).replace(/</g,'\\u003c');
const labels={mbti:'MBTI-style questionnaire',enneagram:'Enneagram questionnaire',disc:'DISC questionnaire',attachment:'Attachment questionnaire','big-five':'Big Five test'};
function page(route,title,description,body,scripts=''){
 return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)} | AgentTune</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="https://agent-tune.com${route}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:url" content="https://agent-tune.com${route}"><meta property="og:image" content="https://agent-tune.com/og/og-card.png"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/styles.css"><script defer src="/consent.js"></script><style>.quiz-page{--lib-accent:#5b4dc0}#quiz-runner{margin-top:24px}#quiz-restart{margin:24px 0}.questionnaire-copy{max-width:760px;margin:32px 0 56px}.questionnaire-copy p{font-size:18px;line-height:1.6}.questionnaire-copy h2{margin-top:32px}.questionnaire-actions{display:flex;flex-wrap:wrap;gap:12px;margin:24px 0}.questionnaire-status{padding:20px;border:1px solid var(--border);border-radius:12px;background:var(--surface,#fff)}.score-list{display:grid;gap:12px;padding:0;list-style:none}.score-list li{padding:16px;border:1px solid var(--border);border-radius:10px}.questionnaire-json{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px}.questionnaire-card-list{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,280px),1fr));gap:18px}.questionnaire-card-list article{padding:24px;border:1px solid var(--border);border-radius:12px;background:white}</style></head><body class="quiz-page"><a class="skip-link" href="#main">Skip to content</a><div class="page"><nav class="nav"><a class="brand" href="/"><span class="brand-dot"></span>AgentTune</a><div class="nav-links"><a href="/library/">Library</a><a href="/tests/" class="active">Tests</a><a href="/research">Research</a><a href="/guides/">Guides</a><a href="/tools/custom-instructions-generator">Generator</a></div></nav><main id="main" tabindex="-1">${body}</main><footer class="footer"><span><a href="/resources/content/THIRD_PARTY_NOTICES.md">Licenses and questionnaire availability</a> · <a href="/privacy">Privacy</a> · <a href="/terms">Terms</a></span><a href="/tests/">All questionnaires</a></footer></div>${scripts}</body></html>\n`;
}
for(const policy of content.rights.instruments.filter(r=>!r.available)){
 const name=labels[policy.route];
 const reasons={mbti:'The published OEJTS terms restrict commercial reuse. We are reviewing permission for AgentTune’s distribution.',disc:'The published ODAT terms restrict commercial reuse. We are reviewing permission for AgentTune’s distribution.',enneagram:'We have not yet verified the exact redistribution terms for the OEPS version used by AgentTune.',attachment:'ECR-R allows noncommercial research, but permission for product use and redistribution needs to be established.'};
 write('tests/'+policy.route+'.html',page('/tests/'+policy.route,name+' availability','Current questionnaire availability, original sources and editable communication preferences.',`<section class="questionnaire-copy"><p class="pill">Questionnaire availability</p><h1 class="h-hero">${name}</h1><p class="lede">Choose how you want your assistant to respond. You do not need a test result to use a template.</p><div class="questionnaire-status"><h2>Questionnaire currently unavailable</h2><p>${reasons[policy.route]} The question text and interactive test are excluded from this release.</p><p>Your existing preferences still work. You can browse and edit the framework’s communication templates, or build instructions from the behaviors you want.</p></div><div class="questionnaire-actions"><a class="btn btn-primary" href="/tools/custom-instructions-generator">Choose my preferences →</a><a class="btn btn-secondary" href="/library/">Browse templates</a></div><h2>Sources and alternatives</h2><p><a href="${esc(policy.evidence_urls[0])}">Read the original publisher’s documentation</a>. Its terms apply to any use there. The <a href="/tests/big-five">IPIP Big Five adaptation</a> remains available on AgentTune.</p><p>Templates are editorial communication suggestions, not diagnoses or validated performance improvements. Historical research used version-specific adaptations and has not been relabeled as a corrected instrument.</p><p><a href="/tests/${policy.route}.md">Availability in Markdown</a> · <a href="/resources/content/instrument-rights.json">Instrument rights record</a></p></section>`));
}
const d=content.definitions[0];
const rows=d.items.map(i=>`<tr><td>${esc(i.id)}</td><td>${esc(i.text)}</td><td>${i.dimension}</td><td>${i.reverse?'Yes':'No'}</td></tr>`).join('');
const body=`<section id="quiz-intro" class="questionnaire-copy"><p class="pill">50 questions · about 7 minutes · no signup</p><h1 class="h-hero">Big Five test.</h1><p class="lede">Reflect on your typical behavior with this IPIP adaptation. Your answers stay in this browser; results show five scores, without assigning instructions or a personality type.</p><p>Rate each statement from very inaccurate to very accurate. Complete all 50 questions for a result. Scores are not population percentiles or a diagnosis.</p><button class="btn btn-primary" id="quiz-start" type="button">Start the test →</button><p>Prefer to skip the test? <a href="/tools/custom-instructions-generator">Choose communication preferences directly.</a></p></section>
<section id="quiz-runner" hidden><div class="quiz-progress"><span>Question <span id="quiz-progress-current">1</span> of 50</span><div class="quiz-progress-track"><div id="quiz-progress-bar" class="quiz-progress-bar"></div></div></div><p id="quiz-announcement" class="sr-only" aria-live="polite"></p><div class="quiz-card" id="quiz-card" tabindex="-1"><h2 id="quiz-item-statement"></h2><div class="quiz-likert" role="group" aria-label="How accurately does this describe you?">${d.anchors.map((a,i)=>`<button class="quiz-likert-btn" type="button" data-value="${i+1}" aria-pressed="false"><span class="quiz-likert-num">${i+1}</span><span>${esc(a)}</span></button>`).join('')}</div><p>Choose an answer, or use keys 1–5. Your choice advances to the next statement.</p><button class="btn btn-secondary" type="button" id="quiz-back">← Back</button></div></section>
<section id="quiz-result" hidden class="questionnaire-copy"><h2 id="quiz-result-code" tabindex="-1">Your Big Five scores</h2><p>Each total runs from 10 to 50; the item average runs from 1 to 5. Bars show position within the possible score range, not your position in a population.</p><ul id="quiz-result-scores" class="score-list"></ul><p>Neuroticism uses the opposite scoring direction to IPIP’s Emotional Stability factor. Openness corresponds to its Intellect/Imagination factor. This adaptation is not a clinical assessment.</p><div class="questionnaire-actions"><a href="/tools/custom-instructions-generator" class="btn btn-primary">Choose my communication preferences →</a><a href="/library/" class="btn btn-secondary">Browse templates</a></div><p>No instructions are selected automatically from these scores. Review the wording of any template before using it.</p><details><summary>View or save your result</summary><pre id="quiz-result-json" class="questionnaire-json"></pre><div class="questionnaire-actions"><button id="quiz-copy-tuning" type="button" class="btn btn-secondary">Copy result JSON</button><button id="quiz-download-tuning" type="button" class="btn btn-secondary">Download result JSON</button></div></details></section><button id="quiz-restart" class="btn btn-secondary" type="button" hidden>Start over</button>
<details class="questionnaire-copy"><summary>Instrument, questions and scoring</summary><p>Instrument <code>${d.id}@${d.version}</code>; scorer 1.0.0. <a href="/tests/big-five.md">Markdown specification</a> · <a href="/resources/scoring/README.md">Local scoring API</a> · <a href="${d.source}">IPIP source</a>.</p><p>Reverse items use 6 minus the raw response. Sum the ten scored items for each dimension, then divide by ten for its mean. Missing responses produce no final score. Duplicate, invalid or out-of-range answers are rejected. The IPIP items are public domain; <a href="https://ipip.ori.org/newPermission.htm">see source terms</a>.</p><div class="quiz-spec-table-scroll" role="region" aria-label="Questionnaire items" tabindex="0"><table class="score-table"><thead><tr><th>ID</th><th>Statement (I…)</th><th>Dimension</th><th>Reverse</th></tr></thead><tbody id="quiz-spec-items">${rows}</tbody></table></div></details>`;
const script=`<script src="/quiz-utils.js"></script><script src="/resources/scoring/score.js"></script><script>
(function(){
const ITEMS = ${inline(d.items)};
const instrumentId=${inline(d.id)},instrumentVersion=${inline(d.version)};
const state={currentIndex:0,answers:new Array(50).fill(null),currentTuning:'',resultVersion:0};
const $=id=>document.getElementById(id);
const advance = window.ATQuiz.transition();
const draft=window.ATQuiz.draft(document,state,50,5,instrumentId+'@'+instrumentVersion);
function start(){ $('quiz-intro').hidden=true;$('quiz-result').hidden=true;$('quiz-runner').hidden=false;$('quiz-restart').hidden=false;renderQuestion();window.ATQuiz.focusScreen(document); }
draft.bind(start);
$('quiz-start').addEventListener('click',()=>{state.currentIndex=0;start();if(window.atTrack)window.atTrack('quiz_start');});
function renderQuestion(){advance.cancel();draft.save();const item=ITEMS[state.currentIndex];$('quiz-progress-current').textContent=state.currentIndex+1;$('quiz-progress-bar').style.width=(state.currentIndex/50*100)+'%';$('quiz-item-statement').textContent='I '+item.text.charAt(0).toLowerCase()+item.text.slice(1);document.querySelectorAll('.quiz-likert-btn').forEach(b=>{const selected=Number(b.dataset.value)===state.answers[state.currentIndex];b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',String(selected));});$('quiz-back').disabled=state.currentIndex===0;window.ATQuiz.focusQuestion(document,state.currentIndex,50);}
function selectAnswer(value){if($('quiz-runner').hidden)return;if(!advance.schedule(()=>{if(state.currentIndex<49){state.currentIndex++;renderQuestion();}else showResult();}))return;state.answers[state.currentIndex]=value;draft.save();document.querySelectorAll('.quiz-likert-btn').forEach(b=>{const on=Number(b.dataset.value)===value;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',String(on));});}
document.querySelectorAll('.quiz-likert-btn').forEach(b=>b.addEventListener('click',e=>{if(e.detail>1)return;selectAnswer(Number(b.dataset.value));}));
$('quiz-back').addEventListener('click',()=>{advance.cancel();if(state.currentIndex>0){state.currentIndex--;renderQuestion();}});
document.addEventListener('keydown',e=>{if(window.ATQuiz.ignoreShortcut(e)||$('quiz-runner').hidden)return;if(/^[1-5]$/.test(e.key)){e.preventDefault();selectAnswer(Number(e.key));}else if(e.key==='Backspace'){e.preventDefault();$('quiz-back').click();}});
function computeResult(answers){const out=window.AgentTuneScoring.scoreOrdered(instrumentId,instrumentVersion,answers);return {...out,raw:out.values};}
function showResult(){const result=computeResult(state.answers);if(result.status!=='complete'){return;}$('quiz-runner').hidden=true;$('quiz-result').hidden=false;draft.clear();state.resultVersion++;const names={O:'Openness',C:'Conscientiousness',E:'Extraversion',A:'Agreeableness',N:'Neuroticism'};$('quiz-result-scores').innerHTML=Object.entries(result.values).map(([k,v])=>'<li><strong>'+names[k]+'</strong> — '+v+'/50 · average '+result.means[k].toFixed(1)+'/5<div class="quiz-axis-bar"><div class="quiz-axis-fill" style="width:'+((v-10)/40*100)+'%"></div></div></li>').join('');delete result.raw;state.currentTuning=JSON.stringify(result,null,2);$('quiz-result-json').textContent=state.currentTuning;if(window.atTrack)window.atTrack('quiz_complete');window.ATQuiz.focusScreen(document);}
$('quiz-copy-tuning').addEventListener('click',()=>{if(state.currentTuning)window.ATQuiz.copyTuning(state.currentTuning,$('quiz-copy-tuning'));});
$('quiz-download-tuning').addEventListener('click',()=>{if(!state.currentTuning)return;const url=URL.createObjectURL(new Blob([state.currentTuning],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='agenttune-ipip50-result.json';document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);});
$('quiz-restart').addEventListener('click',()=>{advance.cancel();draft.clear();state.resultVersion++;state.currentIndex=0;state.answers=new Array(50).fill(null);state.currentTuning='';$('quiz-result-json').textContent='';$('quiz-result').hidden=true;$('quiz-runner').hidden=true;$('quiz-intro').hidden=false;$('quiz-restart').hidden=true;window.ATQuiz.focusScreen(document);});
})();</script>`;
write('tests/big-five.html',page('/tests/big-five','Big Five test — scores, not labels','A 50-item IPIP adaptation with local scoring, raw dimension totals and item averages. No signup or automatic personality tuning.',body,script));
write('tests/index.html',page('/tests/','Personality questionnaires and availability','Take the available IPIP Big Five adaptation or choose communication preferences directly. Review availability and terms for other questionnaires.',`<section class="questionnaire-copy"><h1 class="h-hero">Start with your preferences.</h1><p class="lede">A questionnaire can help you reflect. You can also choose the tone, detail and structure you want without a test.</p><a class="btn btn-primary" href="/tools/custom-instructions-generator">Build my instructions →</a><h2>Questionnaires</h2><p>Big Five is currently available. Other questionnaires are paused while we verify rights for their distribution; their communication templates remain available.</p></section><div class="questionnaire-card-list">${content.rights.instruments.map(p=>`<article><p class="pill">${p.available?'Available · public-domain items':'Questionnaire unavailable'}</p><h2><a href="/tests/${p.route}">${labels[p.route]}</a></h2><p>${p.available?'50 questions. Raw totals and item averages; no population percentiles.':'Read the availability note, find the original publisher and choose a communication template.'}</p><a href="/tests/${p.route}">${p.available?'Take the test':'View availability'} →</a></article>`).join('')}</div><section class="questionnaire-copy"><p><a href="/resources/content/instrument-rights.json">Instrument rights</a> · <a href="/resources/content/CHANGELOG.md">Version and migration notes</a></p></section>`));
console.log('Rendered one versioned quiz and four questionnaire availability pages.');
